### ISSUE TITLE
compilation issue

### ISSUE THREAD

**Issue by MathieuCGit** [cfillion/reapack-index#15]
Hello

I'm trying to install reapack-index on a debian 12 server. I've actually installed some dev packages : 
`sudo apt install ruby ruby-dev make cmake pkg-config build-essential libssl-dev libgit2-dev git ruby-gssapi heimdal-dev`

Compilation seems to work but I encounter a strange issue at the end, here is the end output of the `mkmf.log`

```
[ 99%] Building C object src/util/CMakeFiles/util.dir/hash/sha1dc/ubc_check.c.o
[100%] Building C object src/util/CMakeFiles/util.dir/hash/openssl.c.o
[100%] Built target util
[100%] Linking C static library ../../libgit2.a
[100%] Built target libgit2package
LD_LIBRARY_PATH=/var/lib/gems/3.1.0/gems/rugged-1.7.2/ext/rugged/../../vendor/libgit2/build:.:/usr/lib/x86_64-linux-gnu "x86_64-linux-gnu-gcc -o conftest -I/usr/include/x86_64-linux-gnu/ruby-3.1.0 -I/usr/include/ruby-3.1.0/ruby/backward -I/usr/include/ruby-3.1.0 -I. -I/var/lib/gems/3.1.0/gems/rugged-1.7.2/ext/rugged/../../vendor/libgit2/include -Wdate-time -D_FORTIFY_SOURCE=2   -g -O2 -Werror=implicit-function-declaration -ffile-prefix-map=BUILDDIR=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -fPIC  -g -Wall -Wno-comment conftest.c  -L/var/lib/gems/3.1.0/gems/rugged-1.7.2/ext/rugged/../../vendor/libgit2/build -L. -L/usr/lib/x86_64-linux-gnu -L. -Wl,-z,relro -Wl,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,--no-as-needed -L/usr/local/lib -lgit2 -lrt -lssl -lz -lzstd -ldl -pthread -lcrypto -lzstd -ldl -pthread -lz     -lruby-3.1  -lm  -lc"
/usr/bin/ld: cannot find -lzstd: No such file or directory
/usr/bin/ld: cannot find -lzstd: No such file or directory
collect2: error: ld returned 1 exit status
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */
```

and here is the console output
```
Building native extensions. This could take a while...
ERROR:  Error installing reapack-index:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/3.1.0/gems/rugged-1.7.2/ext/rugged
/usr/bin/ruby3.1 -I/usr/lib/ruby/vendor_ruby extconf.rb

[...]

-- Enabled features:
 * nanoseconds, support nanosecond precision file mtimes and ctimes
 * HTTPS, using OpenSSL
 * SHA1, using CollisionDetection
 * SHA256, using OpenSSL
 * http-parser, http-parser support (bundled)
 * regex, using bundled PCRE
 * xdiff, xdiff support (bundled)
 * zlib, using system zlib
 * futimens, futimens support
 * threadsafe, threadsafe support
 * ntlmclient, NTLM authentication support for Unix

-- Disabled features:
 * SHA256 API, experimental SHA256 APIs
 * debugpool, debug pool allocator
 * debugalloc, debug strict allocators
 * debugopen, path validation in open
 * GSSAPI, GSSAPI support for SPNEGO authentication
 * SSH, SSH transport support
 * iconv, iconv encoding conversion support

-- Configuring done (4.4s)
-- Generating done (0.0s)
-- Build files have been written to: /var/lib/gems/3.1.0/gems/rugged-1.7.2/vendor/libgit2/build
 -- /usr/bin/gmake
checking for -lgit2... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)3.1
        --with-sha1dc
        --without-sha1dc
        --with-ssh
        --without-ssh
        --use-system-libraries
        --with-git2-dir
        --without-git2-dir
        --with-git2-include
        --without-git2-include=${git2-dir}/include
        --with-git2-lib
        --without-git2-lib=${git2-dir}/lib
        --with-git2lib
        --without-git2lib
/usr/lib/ruby/3.1.0/mkmf.rb:498:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/lib/ruby/3.1.0/mkmf.rb:591:in `try_link0'
        from /usr/lib/ruby/3.1.0/mkmf.rb:609:in `try_link'
        from /usr/lib/ruby/3.1.0/mkmf.rb:837:in `try_func'
        from /usr/lib/ruby/3.1.0/mkmf.rb:1065:in `block in have_library'
        from /usr/lib/ruby/3.1.0/mkmf.rb:1007:in `block in checking_for'
        from /usr/lib/ruby/3.1.0/mkmf.rb:362:in `block (2 levels) in postpone'
        from /usr/lib/ruby/3.1.0/mkmf.rb:332:in `open'
        from /usr/lib/ruby/3.1.0/mkmf.rb:362:in `block in postpone'
        from /usr/lib/ruby/3.1.0/mkmf.rb:332:in `open'
        from /usr/lib/ruby/3.1.0/mkmf.rb:358:in `postpone'
        from /usr/lib/ruby/3.1.0/mkmf.rb:1006:in `checking_for'
        from /usr/lib/ruby/3.1.0/mkmf.rb:1060:in `have_library'
        from extconf.rb:140:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/3.1.0/extensions/x86_64-linux/3.1.0/rugged-1.7.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/3.1.0/gems/rugged-1.7.2 for inspection.
Results logged to /var/lib/gems/3.1.0/extensions/x86_64-linux/3.1.0/rugged-1.7.2/gem_make.out
```

So I guess I missed something (dependencies ??), but what ???

**Comment by cfillion** [comment]
The error messages says zstd. `libzstd-dev`?

**Comment by MathieuCGit** [comment]
oh dude....so obvious...thanks man !

BTW maybe could you add the dependencies into the README.md ? Here is the command line it should fit the needs for debian users, feel free to fix missing stuff  : 
` sudo apt install ruby ruby-dev make cmake pkg-config build-essential libssl-dev libgit2-dev git ruby-gssapi heimdal-dev libzstd-dev`

**Comment by MathieuCGit** [comment]
"The only thing worse than being blind is having sight but no vision." ...
