### ISSUE TITLE
Error running version 1.2.1

### ISSUE THREAD

**Issue by Claudiohbsantos** [cfillion/reapack-index#3]
I'm getting an error when running reapack-index v1.2.1in a repository where reapack-index v1.2 runs without a problem. For now I just reverted to 1.2 but thought I'd report in case it helps. 

**Platform:** Windows 10
**Ruby:** ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]

```
Indexing commit 3 of 3 (100%)...K:/Programs/Ruby23/lib/ruby/gems/2.3.0/gems/reapack-index-1.2.1/lib/reapack/index/scanner.rb:112:in `make_url': uninitialized constant ReaPack::Index::Scanner::URI (NameError)
        from K:/Programs/Ruby23/lib/ruby/gems/2.3.0/gems/reapack-index-1.2.1/lib/reapack/index/scanner.rb:162:in `block (2 levels) in parse_provides'
        from K:/Programs/Ruby23/lib/ruby/gems/2.3.0/gems/reapack-index-1.2.1/lib/reapack/index/scanner.rb:147:in `map'
        from K:/Programs/Ruby23/lib/ruby/gems/2.3.0/gems/reapack-index-1.2.1/lib/reapack/index/scanner.rb:147:in `block in parse_provides'
        from K:/Programs/Ruby23/lib/ruby/gems/2.3.0/gems/reapack-index-1.2.1/lib/reapack/index/provides.rb:21:in `block in parse_each'
        from K:/Programs/Ruby23/lib/ruby/gems/2.3.0/gems/reapack-index-1.2.1/lib/reapack/index/provides.rb:21:in `map'
        from K:/Programs/Ruby23/lib/ruby/gems/2.3.0/gems/reapack-index-1.2.1/lib/reapack/index/provides.rb:21:in `parse_each'
        from K:/Programs/Ruby23/lib/ruby/gems/2.3.0/gems/reapack-index-1.2.1/lib/reapack/index/scanner.rb:121:in `each'
        from K:/Programs/Ruby23/lib/ruby/gems/2.3.0/gems/reapack-index-1.2.1/lib/reapack/index/scanner.rb:121:in `map'
        from K:/Programs/Ruby23/lib/ruby/gems/2.3.0/gems/reapack-index-1.2.1/lib/reapack/index/scanner.rb:121:in `parse_provides'
        from K:/Programs/Ruby23/lib/ruby/gems/2.3.0/gems/reapack-index-1.2.1/lib/reapack/index/scanner.rb:80:in `block (2 levels) in run'
        from K:/Programs/Ruby23/lib/ruby/gems/2.3.0/gems/reapack-index-1.2.1/lib/reapack/index/version.rb:60:in `replace_sources'
        from K:/Programs/Ruby23/lib/ruby/gems/2.3.0/gems/reapack-index-1.2.1/lib/reapack/index/scanner.rb:78:in `block in run'
        from K:/Programs/Ruby23/lib/ruby/gems/2.3.0/gems/reapack-index-1.2.1/lib/reapack/index/package.rb:98:in `version'
        from K:/Programs/Ruby23/lib/ruby/gems/2.3.0/gems/reapack-index-1.2.1/lib/reapack/index/scanner.rb:69:in `run'
        from K:/Programs/Ruby23/lib/ruby/gems/2.3.0/gems/reapack-index-1.2.1/lib/reapack/index.rb:141:in `scan'
        from K:/Programs/Ruby23/lib/ruby/gems/2.3.0/gems/reapack-index-1.2.1/lib/reapack/index/cli.rb:137:in `process_diff'
        from K:/Programs/Ruby23/lib/ruby/gems/2.3.0/gems/reapack-index-1.2.1/lib/reapack/index/cli.rb:125:in `block in process_commit'
        from K:/Programs/Ruby23/lib/ruby/gems/2.3.0/gems/reapack-index-1.2.1/lib/reapack/index/cli.rb:125:in `each'
        from K:/Programs/Ruby23/lib/ruby/gems/2.3.0/gems/reapack-index-1.2.1/lib/reapack/index/cli.rb:125:in `process_commit'
        from K:/Programs/Ruby23/lib/ruby/gems/2.3.0/gems/reapack-index-1.2.1/lib/reapack/index/cli.rb:102:in `block (2 levels) in do_scan'
        from K:/Programs/Ruby23/lib/ruby/gems/2.3.0/gems/reapack-index-1.2.1/lib/reapack/index/cli.rb:102:in `each'
        from K:/Programs/Ruby23/lib/ruby/gems/2.3.0/gems/reapack-index-1.2.1/lib/reapack/index/cli.rb:102:in `block in do_scan'
        from K:/Programs/Ruby23/lib/ruby/gems/2.3.0/gems/reapack-index-1.2.1/lib/reapack/index/cli.rb:302:in `progress_wrapper'
        from K:/Programs/Ruby23/lib/ruby/gems/2.3.0/gems/reapack-index-1.2.1/lib/reapack/index/cli.rb:101:in `do_scan'
        from K:/Programs/Ruby23/lib/ruby/gems/2.3.0/gems/reapack-index-1.2.1/lib/reapack/index/cli.rb:44:in `run'
        from K:/Programs/Ruby23/lib/ruby/gems/2.3.0/gems/reapack-index-1.2.1/bin/reapack-index:8:in `block in <top (required)>'
        from K:/Programs/Ruby23/lib/ruby/gems/2.3.0/gems/reapack-index-1.2.1/bin/reapack-index:8:in `catch'
        from K:/Programs/Ruby23/lib/ruby/gems/2.3.0/gems/reapack-index-1.2.1/bin/reapack-index:8:in `<top (required)>'
        from K:/Programs/Ruby23/bin/reapack-index:22:in `load'
        from K:/Programs/Ruby23/bin/reapack-index:22:in `<main>'
```

**Comment by cfillion** [comment]
I can't reproduce on any of my machines. I assume this is due to a difference in the installed version of dependent gems (likely `addressable`) and/or Ruby version.

Can you try this fixed version? https://cfillion.ca/files/reapack/reapack-index-1.2.2.gem

**Comment by Claudiohbsantos** [comment]
Yeah, 1.2.2 seems to fix the issue for me. Thanks
